version: '3.8'

services:
  app:
    image: your-quarkus-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://db:5432/tasksdb
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_METRICS_EXPORT_PROMETHEUS_PATH=/q/metrics
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

volumes:
  postgres-data:
